# .gitpod.yml
tasks:
  - name: Setup
    init: |
      docker-compose build
      pip install -r requirements.txt
    command: |
      docker-compose up -d
      sleep 30
      bash create_connectors.sh
      gp sync-done setup

ports:
  - port: 3000
    onOpen: open-preview
  - port: 5432
    onOpen: ignore
  - port: 8083
    onOpen: ignore
  - port: 9092
    onOpen: ignore
